pipeline {
    agent {
        kubernetes {
            label 'my-pod-template'
            defaultContainer 'jnlp'
            yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
  - name: maven
    image: maven:alpine
    command:
    - cat
    tty: true
"""
        }
    }
    stages {
        stage('Build') {
            steps {
                sh """
        echo "Repo Owner:          ${repoOwner}"
        echo "Repo Name :          ${repoName}"
        echo "Repo Creds:          ${repoCreds}"
        echo "Image Org:           ${imageOrg}"
        echo "Docker Repo:         ${imageRepo}"
        """
            }
        }
        stage('Run maven') {
            steps {
                container('maven') {
                    sh "hostname"
                }
            }
        }
        stage('Build with Kaniko') {
            steps {
                container(name: 'kaniko', shell: '/busybox/sh') {
                    withEnv(['PATH+EXTRA=/busybox']) {
                        sh "pwd"
                        sh "ls"
                        sh '''#!/busybox/sh
                           /kaniko/executor --context `pwd` --destination $DOCKER_DEST/gapi:$BMAJOR.$BUILD_ID
                        '''
                    }
                }
            }
        }
    }
}

