pipeline {

    agent {
            kubernetes {
                label 'gapi-build'
                defaultContainer 'jnlp'
                yamlFile 'KubernetesPod.yaml'
            }
        }
    environment {
      intDebug="${debugPL}"
    }
    stages {
        stage('DebugOnly') {
            when {
              environment name: 'intDebug', value: 'true'
            }
            steps {
                sh """
        echo "Repo Owner:          ${repoOwner}"
        echo "Repo Name :          ${repoName}"
        echo "Repo Creds:          ${repoCreds}"
        echo "Image Org:           ${imageOrg}"
        echo "Image Repo:          ${imageRepo}"
        echo "Major Build Label:   ${majorBuildLabel}"
        """
            }
        }

        stage('Build with Kaniko') {
            steps {
                container(name: 'kaniko', shell: '/busybox/sh') {
                    withEnv(['PATH+EXTRA=/busybox']) {

                        sh """#!/busybox/sh

                           /kaniko/executor --context `pwd` --destination $imageOrg/$imageRepo:$majorBuildLabel.$BUILD_ID
                        """
                    }
                }
            }
        }
    }
}

