pipeline {
    agent {
        kubernetes {
            yaml """
            apiVersion: v1
            kind: Pod
            spec:
              containers:
              - name: jnlp
                image: jenkins/inbound-agent:4.10-1
                args: ['\$(JENKINS_SECRET)', '\$(JENKINS_NAME)']
              - name: build
                image: maven:3.8.1-jdk-11
                command:
                - cat
                tty: true
            """
        }
    }

    stages {
        stage('Build') {
            steps {
                container('build') {
                    sh 'mvn --version'
                }
            }
        }

        stage('Test') {
            steps {
                container('build') {
                    sh 'mvn test'
                }
            }
        }
    }
}
