pipeline {
    agent {
        kubernetes {
            yaml """
            apiVersion: v1
            kind: Pod
            spec:
              containers:
              - name: busybox
                image: busybox
                command:
                - cat
                tty: true
            """
        }
    }
    
    stages {
        stage('Run on Kubernetes') {
            steps {
                container('busybox') {
                    sh 'echo "Running on Kubernetes!"'
                    sh 'uname -a'
                }
            }
        }
    }
}
