pipeline {
    agent {
        kubernetes {
            label 'my-pod-template'
            defaultContainer 'jnlp'
            yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
  - name: maven
    image: maven:alpine
    command:
    - cat
    tty: true
"""
        }
    }
    stages {
        stage('Build') {
            steps {
                sh """
        echo "these are all variables supplied vis the configuration of each job"
        echo "Repo Owner: ${repoOwner}"
        echo "Repo Name : ${repoName}"
        echo "Repo Creds: ${repoCreds}"
        """
            }
        }
        stage('Run maven') {
            steps {
                container('maven') {
                    configFileProvider([configFile(fileId: 'mvn_set', variable: 'MAVEN_SETTINGS_XML')]) {
                        sh "mvn -s $MAVEN_SETTINGS_XML compile"
                    }
                }
            }
        }
    }
}

